<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://service.durgasoft.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://service.durgasoft.com" xmlns:intf="http://service.durgasoft.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="CalService">

   </wsdl:portType>

   <wsdl:binding name="CalServiceSoapBinding" type="impl:CalService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="CalServiceService">

      <wsdl:port binding="impl:CalServiceSoapBinding" name="CalService">

         <wsdlsoap:address location="http://localhost:8080/CalculatorService/services/CalService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
